### ISSUE TITLE
hw01 ready for grading

### ISSUE THREAD

**Issue by Shirlett** [Shirlett/STAT545-hw01-Hall-Shirlett#1]
@vincenzocoia @gvdr @ksedivyhaley @joeybernhardt @mynamedaike @pgonzaleze @derekcho

**Comment by JoeyBernhardt** [comment]
Correctly named issue: Yes
Link to work to be reviewed: in README
Use 4 or more aspects of markdown: Yes (headings, list, formatting, gifs)
Reflections / how it was done: Yes
Gapminder exploration: Yes

Comments:

Very nicely done! Nice use of images, links and gifs! Reflections on the process were nicely detailed as well. Gapminder exploration was good, although next time, I recommend adding a little narrative about the figures are saying -- is there anything surprising in there? What story do they tell?

Note: your mark will be sent out later.
